CREATE TABLE `episodes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `episodeid` int(11) DEFAULT NULL,
  `tvshowid` int(11) DEFAULT NULL,
  `hide` tinyint(4) DEFAULT '0',
  `refresh` smallint(6) DEFAULT '0',
  `title` text,
  `thumb` text,
  `originaltitle` text,
  `rating` decimal(10,2) DEFAULT NULL,
  `writer` text,
  `director` text,
  `cast` text,
  `plot` text,
  `playcount` smallint(6) DEFAULT NULL,
  `episode` smallint(6) DEFAULT NULL,
  `firstaired` date DEFAULT NULL,
  `lastplayed` datetime DEFAULT NULL,
  `dateadded` datetime DEFAULT NULL,
  `votes` int(11) DEFAULT NULL,
  `file` text,
  `showtitle` text,
  `season` smallint(6) DEFAULT NULL,
  `audio` text,
  `video` text,
  `runtime` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_episodeid` (`episodeid`),
  KEY `ix_tvshowid` (`tvshowid`)
) ENGINE=InnoDB AUTO_INCREMENT=1542 DEFAULT CHARSET=utf8